# -*- coding: utf-8 -*-
"""Testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TbPM9XBBh5-7X_qLbZixMw2sTVM7P60S
"""

from audiodataset import create_dataloader
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
from mymodel import MyModel
import pandas as pd
import numpy as np
import torch
import os

#test_df = pd.read_csv(os.path.join('data','google_speech_data.csv'))
#test_df = pd.read_csv(os.path.join('data','baseline_data.csv'))
test_df = pd.read_csv(os.path.join('data','surprisal_data.csv'))
test_loader = create_dataloader(test_df, batch_size = 64)

# init model
num_classes = 5
model = MyModel(num_classes=num_classes)

model_path = 'model/model_epoch_30.pth'
# Load the weights
model.load_state_dict(torch.load(model_path))

# Set the model to evaluation mode
model.eval()

all_labels = []
all_preds = []

with torch.no_grad():
    for inputs, labels in test_loader:
        outputs = model(inputs)
        _, preds = torch.max(outputs, 1)
        labels_int = [int(label) for label in labels]
        labels = torch.tensor(labels_int)
        all_labels.extend(labels.numpy())
        all_preds.extend(preds.numpy())

all_labels = np.array(all_labels)
all_preds = np.array(all_preds)

cm = confusion_matrix(all_labels, all_preds)
print(np.trace(cm) / np.sum(cm)*100)

""" Plot confusion matrix for paper"""

# Define class names for better visualization
class_names = ['neutral', 'happy', 'sad', 'scared', 'angry']

# Display the confusion matrix
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_names)
disp.plot(cmap=plt.cm.Blues, values_format='d', text_kw={'fontsize': 14})
plt.title('Confusion Matrix Test Dataset', fontsize = 15) 
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.xlabel('Predicted label', fontsize = 15)
plt.ylabel('True label', fontsize = 15)
plt.show()

""" Графици на српском"""
# Define class names for better visualization
class_names = ['неутрално', 'срећно', 'тужно', 'уплашено', 'љуто']
# Display the confusion matrix
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_names)
disp.plot(cmap=plt.cm.Blues, values_format='d', text_kw={'fontsize': 14})

# Add title and axis labels
plt.title('Конфузиона матрица тест скупа података', fontsize=15)
plt.xticks(fontsize=12, rotation=45, ha="right")  # Rotate x-axis labels for better readability
plt.yticks(fontsize=12)
plt.xlabel('Предикције модела', fontsize=15)
plt.ylabel('Стварна класа', fontsize=15)

plt.tight_layout()  # Adjust layout to ensure labels fit within the plot
plt.show()