# -*- coding: utf-8 -*-
"""Testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TbPM9XBBh5-7X_qLbZixMw2sTVM7P60S
"""

from audiodataset import create_dataloader
from sklearn.metrics import confusion_matrix
import pandas as pd
import os
import numpy as np
from mymodel import MyModel
import torch.optim as optim
import torch.nn as nn
import torch
import csv

test_df = pd.read_csv(os.path.join('data', 'test_dataset.csv'))
test_loader = create_dataloader(test_df, batch_size = 64)

# init model
num_classes = 5
model = MyModel(num_classes=num_classes)

model_path = f'model/model_epoch_30.pth'
# Load the weights
model.load_state_dict(torch.load(model_path))

# Set the model to evaluation mode
model.eval()

all_labels = []
all_preds = []

with torch.no_grad():
    for inputs, labels in test_loader:
        outputs = model(inputs)
        _, preds = torch.max(outputs, 1)
        labels_int = [int(label) for label in labels]
        labels = torch.tensor(labels_int)
        all_labels.extend(labels.numpy())
        all_preds.extend(preds.numpy())

all_labels = np.array(all_labels)
all_preds = np.array(all_preds)

conf_matrix = confusion_matrix(all_labels, all_preds)
print(conf_matrix)


correct_predictions = np.trace(conf_matrix)
total_instances = np.sum(conf_matrix)
print(correct_predictions / total_instances*100)